jrnl-org/jrnl

jrnl/DayOneJournal.py
jrnl/install.py

Fix two issues with DayOne compatibility:
**Duplicate entries when using Linux to edit DayOne journals**
Python's uuid.uuid1 returns a lowercase uuid string by default, but DayOne
saves it's filenames using an uppercase UUID by default.
On OS X (and I believe windows) filesystems case is preserved, but not
enforced, so using jrnl on a DayOne jrnl file works as expected.  On Linux
however, filesystem case is strictly enforced. As a result when jrnl and DayOne
interact duplicate files get created--one copy with uppercase UUIDs and one
with lowercase.
**Installer doesn't finish if you point it an an existing DayOne journal**
If you specify the top-level diectory of your DayOne journal during install
jrnl dies because it is expecting a file.

Correct issue #259, also fix issue with specifying DayOne journals in install

---

jrnl/util.py

Knowing fully that I may have just added another layer of impropriety, the above line fixed the charset errors I was getting.
I'll illustrate this change with an example string "**Charšet**", entered (e.g. through stdin) in UTF-8 encoding.
To the best of my knowledge, the previous version would first have encoded this string to `Char\xc5\xa1et` (i.e., it encoded each byte not in ascii range as a hex escape code), and then have parsed this string to `CharÅ¡et` (i.e. after "r" it sees Unicode code point U+00c5 and U+00a1).
My version simply takes this str for what it is: an UTF-8 representation of the unicode string `Charšet`.
(This is a rebased duplicate of PR 336 because I cound't figure out how to update the original.)

Fix improper charset handling in PY2 path of u(x)

---

jrnl/upgrade.py

Fixes:
- I use a unicode character in my `~/.jrnl_config` which breaks the upgrade check, fixed by using `codecs.open` on the config file.
- I've manually set my journal paths as `~/jrnl/default.txt` which was working fine for me in 1.0, but the upgrade to 2.0 wasn't expanding that tilde.
Fixes #406

Support unicode and userdir expansion in config during 2.0 upgrade

---

jrnl/Entry.py

The current behavior of text wrapping continues to be borken, despite my previous attempts to submit fixes. This PR solves *all* the pretty printed text wrapping issues, very pythonically I think, and fixes #222 more simply than any other existing fix I've seen, such as 060565c.
After this PR, with perfect whitespace and indent handling:
Before, on the current 2.0-rc1 branch, with `drop_whitespace=True`:
Before, on the master (1.0) branch, with `drop_whitespace=False`:

Clean up text wrapping once and for all --- Please!

---

jrnl/util.py

This fixes the problem where an exported entry will have extra whitespace depending on if it was the last entry or a previous entry.
For example, a git hook that commits changes will always commit a new whitespace change for the previous entry with every new entry.

Fully strip title and body after SENTENCE_SPLITTER search

---

features/data/configs/basic.yaml
features/data/configs/bug153.yaml
features/data/configs/bug343.yaml
features/data/configs/dayone.yaml
features/data/configs/empty_folder.yaml
features/data/configs/encrypted.yaml
features/data/configs/encrypted_old.yaml
features/data/configs/markdown-headings-335.yaml
features/data/configs/multiple.yaml
features/data/configs/tags-216.yaml
features/data/configs/tags-237.yaml
features/data/configs/tags.yaml
jrnl/Entry.py
jrnl/Journal.py
jrnl/install.py

I really like unicode box characters... This PR allows the user to define what character to use for the indent. I like the light vertical box char -- on my terminal, it displays as an unbroken line on the left margin -- much nicer than the pipe char.

User defined indent character

---

docs/encryption.rst
docs/installation.rst

- remove extraneous word "you" in zsh note
- instruct user to set `HISTIGNORE` while maintaining their existing `HISTIGNORE`
- minor whitespace change

Minor Documentation Fixes

---

features/steps/core.py
setup.py

The keyring package broke backward compatibility in version 8.0 by
moving some keyring backends to another package, keyrings.alt, as
documented in the [changelog](https://pythonhosted.org/keyring/history.html#id22).
This change broke behave tests which were trying to use
keyring.backends.file.PlaintextKeyring - no longer existing in keyring
package.
This commit adds the keyrings.alt package as dependency so that the
PlaintextKeyring class can be used.

Fix failing behave tests

---

docs/recipes.rst

Hi, 
I've recently started using Jrnl and I like it a lot! Thanks so much for making this great software.
I'm using iA Writer as my editor, and I noticed the instructions in the jrnl docs are a little bit out of date. I just bought the newest version and it seems the bundle identifier has changed. This PR updates the id and adds some instructions on how to find a bundle id, in case it changes again.

Update iA Writer bundle id

---

setup.py

Behave tests were failing in `2.0-rc1` branch with 
```
ImportError: No module named 'asteval'
```
This commit adds the `asteval` dependency to `setup.py` to fix the failing tests. I chose the required asteval by setting it to my current installed version, because I didn't know what other version to put there. Feel free to change it.
Behave still fails for python 2.7, but that seems to be an unrelated issue.

Fix behave tests by adding asteval python dependency

---

jrnl/plugins/template_exporter.py

If template_explorer.py was imported in python2, it would fail because
it uses unicode_literals which would ultimately cause passing an unicode
string as the first argument to the 'type' built-in function.
This commit fixes this by converting the unicode to string before it is
passed to the 'type' function.
Fixes #456

Fix python2 error in template_explorer.py

---

jrnl/cli.py

If the journal is encrypted, jrnl asks for a password using the
getpass.getpass function. If user presses the keyboard interrupt (e.g.
ctrl+c) during the password prompt, jrnl crashes and prints a stack
trace. This however is not very user friendly.
This commit adds a check for KeyboardInterrupt Exception and prints a
message whenever this exception occurs and exits. Stack is no longer
printed.
Fixes #450

Catch keyboard interrupt when opening journal

---

.travis.yml

The --use-mirrors pip switch [does not work](https://pip.pypa.io/en/stable/news/) since pip 7.0.0. This caused
travis builds to fail.
This commit removes the --use-mirrors switch.

Remove --use-mirrors switch from travis setup

---

docs/recipes.rst

Trying to rebase with your remote 2.0-rc1 branch, and my local 2.0-rc1 branch was returning multiple conflicts and I was more than a little worried about introducing error. 
Since my PR was a single commit, I think cherry-picking it from my patch-1 branch into the 2.0-rc1 branch is safer.

Add instructions for VS Code

---

jrnl/util.py

Fixes the problem with permissions when trying to use an external editor to edit old entries on Windows.

Added @hollystyles' fix for Issue #415

---

.travis.yml

TravisCI has migrated their infrastructure: https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration

Remove sudo: from .travis.yml

---

features/steps/core.py
jrnl/plugins/template.py
jrnl/util.py

I just went with the default yaml loader, which is what the code is currently using anyway.

Fix issue #584 YAMLLoadWarning

---

CONTRIBUTING.md
README.md

And ensuring the URLs are valid (except build badge)

[GH-598] Changing references from jrnl-plus back to jrnl

---

setup.py

This is the smallest fix possible for #610. I want to avoid changing the dependency management until we have time to vet all of the updated dependencies.

Unpin crypto #610

---

features/data/configs/brackets.yaml
features/data/configs/mostlyreadabledates.yaml
features/data/configs/unreadabledates.yaml
features/data/journals/brackets.journal
features/data/journals/mostlyreadabledates.journal
features/data/journals/unreadabledates.journal
features/regression.feature
jrnl/Journal.py
jrnl/time.py

This adds a few changes to the way jrnl reads dates and entries:
- Assume any value in brackets but 6 characters or less isn't a date but is instead part of the current entry. This is useful for markdown footnotes as mentioned in GH-614
- If a journal has only unreadable dates, assume that it's one entry (instead of ignoring its contents completely, which could lead to deletion in future jrnl calls)

[GH-614] resolving issues around unreadable dates

---

.github/stale.yml

We will increase this again later, but we want to clean out the backlog of old issues
sooner, if possible. This will allow us to do that.

reduce the number of days an issue can be open with no activity before marked stale

---

features/data/journals/simple_jrnl-1-9-5.journal
features/regression.feature
jrnl/Journal.py

Lines that have dates in square brackets at the start of the line were confusing
the new date format. With this update, LegacyJournal now looks for those lines
and escapes them by simply adding a space at the start of the line.
A space seems like the least intrusive way to escape entries of this format.

#631 Escape data in square brackets

---

features/exporting.feature
jrnl/plugins/markdown_exporter.py
jrnl/plugins/yaml_exporter.py

Re-create #506, re-based to the current 2.0-rc3 master branch.
Closes #487, Closes #506 
Switches from ATX to 'Hashmark' style Markdown headers for single file markdown exports.
(I tried to force-push to the branch to update #506, but just managed to close PR. Oops!)

Switch to hashmark Markdown headers on export (Mk II)

---

docs/encryption.md

This will modify http://jrnl.sh/encryption.html.
I use the [fish shell](https://fishshell.com/), so I had to look this up for myself. Might as well share it.

In Encryption docs, explain how to prevent Fish history logging

---

features/encryption.feature
features/regression.feature
features/upgrade.feature
jrnl/Journal.py
jrnl/install.py
jrnl/upgrade.py

And aborting upgrade if not.
This change also moves upgrade-related tests into their own upgrade.feature file.

[GH-632] confirming that each journal can be parsed during upgrade

---

jrnl/cli.py
jrnl/install.py
jrnl/upgrade.py
jrnl/util.py

Don't throw exception on Ctrl-C, simply abort.

Handle KeyboardInterrupt when installing journal

---

features/tagging.feature
jrnl/Journal.py
jrnl/cli.py

This change adds a new flag to exlude all tags after it. A rough example:
```
-> jrnl @wat --short
2019-07-25 18:16 @todo @wat wat2
2019-07-27 18:25 @todo @wat @not test
2019-07-28 21:54 @todo @wat wat2
-> jrnl @wat -not @not --short
2019-07-25 18:16 @todo @wat wat2
2019-07-28 21:54 @todo @wat wat2
```

Add '-not' flag for excluding tags from filter

---

setup.py

FullLoader only available from v5.1 : https://pyyaml.org/wiki/PyYAML#history
In a lower version of pyYAML FullLoader  doesn't exist and jrnl doesn't work.

Change pyYAML required version

---

jrnl/plugins/__init__.py
jrnl/plugins/fancy_exporter.py

Just for fun, I created an exporter that formats entries into unicode boxes. It's even more fun when used with [busyloop/lolcat](https://github.com/busyloop/lolcat)!
I only got this to work using `PYTHONIOENCODING=utf-8` though. 
It looks like this:

Add exporter to output entries inside unicode box character boxes

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/Bug_report.md
.github/ISSUE_TEMPLATE/Feature_request.md
.github/ISSUE_TEMPLATE/Support_request.md
.github/PULL_REQUEST_TEMPLATE.md

I saw that you lacked templates for the different github features (pullrequests and issues) so i wanted to quickly help out as i love the service. I might have made a few typos, but i hope they work. Please supply any corrections and i'll gladly change the PR :smiley:  
It solves issue #668 
*sadly all irrelevant*

Create templates for issues and pull requests

---

jrnl/upgrade.py

It seems that `~` (meaning the user directory) must be explicitly expanded when used on the configuration to successfully upgrade.
I can't test this directly, as I don't have a Mac system locally. I don't think there are any applicable tests to be written.
c.f issue #689

[Upgrade to 2.0] Expand User directory

---

features/encryption.feature
features/environment.py
features/multiple_journals.feature
features/steps/core.py
features/upgrade.feature
jrnl/DayOneJournal.py
jrnl/EncryptedJournal.py
jrnl/Entry.py
jrnl/Journal.py
jrnl/__init__.py
jrnl/__main__.py
jrnl/cli.py
jrnl/export.py
jrnl/install.py
jrnl/plugins/__init__.py
jrnl/plugins/jrnl_importer.py
jrnl/plugins/json_exporter.py
jrnl/plugins/markdown_exporter.py
jrnl/plugins/tag_exporter.py
jrnl/plugins/template.py
jrnl/plugins/template_exporter.py
jrnl/plugins/text_exporter.py
jrnl/plugins/util.py
jrnl/plugins/xml_exporter.py
jrnl/plugins/yaml_exporter.py
jrnl/time.py
jrnl/upgrade.py
jrnl/util.py

This PR should completely remove all the Python 2 compatibility features and other leftovers.
Closes #701, closes #615, fixes #700, might fix #667.
I also removed the wonky testing utilities in jrnl.utils and instead used unittest.mock.patch to simulate user inputs in the tests. It's a bit unusual as well this way, but at least we don't have to mess with replacing std.stdin and sys.stderr and what not. If somebody knows a simpler way to simulate user input that works with builtins.input, getpass.getpass as well as sys.stdin.read, let me know.
This is a bit of a bigger PR, but the tests all pass.

remove py2 remnants and use mocks in tests

---

features/custom_dates.feature
features/data/configs/little_endian_dates.yaml
features/data/configs/upgrade_from_195_little_endian_dates.json
features/data/journals/little_endian_dates.journal
features/data/journals/simple_jrnl-1-9-5_little_endian_dates.journal
features/upgrade.feature
jrnl/Journal.py

Fixes parts of #630 and one source of failure during upgrading to 2.0 (#664).
Ever since version 2.0, when parsing a journal file, jrnl would not use the custom date format string anymore. Instead, it relied on the dateutil library to get the parsing right. This change was made to allow people to change their date format without having to manually change their file. However, this broke some existing date formats like %d.%m.%Y, as it would falsely interpret the month as day and vice versa (when %d <= 12). This commit adds some tests using the little endian date format and fixes the behavior by trying to parse the dates using the custom format first, only falling back to dateutil when needed.
Note that this does not yet allow users to make new entries using the little endian format yet. It …

Fix parsing Journals using a little-endian date format

---

.travis.yml
poetry.lock
pyproject.toml

As discussed in #615, we can and should support Python from version 3.6 and up. This PR:
- adds all supported Python versions to Travis,
- tells poetry and therefore pypi that 3.6+ is supported.

Support Python 3.6+

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/support_request.md

- Modifying issue templates to include a ":new:" label
- This makes it easier to categorize and take action on new issues
- Issues stop being "new" when they're resolved and/or added to a milestone
*
- [n/a] The code change is tested and works locally.
- [n/a] Tests pass. Your PR cannot be merged unless tests pass

Adding :new: label to github issue templates

---

jrnl/util.py

Fix crash when no keyring backend available

---

features/dayone.feature
features/dayone_regressions.feature
features/environment.py

c.f. commit 7cbca9f60f1fb5cc9b8d075f9b101d29d9656936
c.f. commit 2a401823b5ae37d5891548852cecfdec99a8e1c7
As per #358, this re-adds just the DayOne tests.
It also adds a "@skip" tag to be used with tests that we don't want to run. (At one point, this may have been included in `behave`.) It is used here because one of the tests doesn't currently pass.

[Dayone] re-add tests

---

features/regression.feature

Adding a test for a newer bug GH-741 which displays the whole journal when the user runs `jrnl -on today`
PR #665 in 2.1.2 fixes this issue very nicely (thank you @notbalanced) but I wanted to ensure that this very specific test case is included.

[GH-741] adding test for bug that displays all entries -on today

---

jrnl/install.py

This removes autocomplete for Windows users, thus preventing jrnl from crashing on Active Python, which has no readline module. It's only used when entering the path on the install step.
Related issue: #738 

[GH-738] preventing readline usage on Windows 

---

.travis.yml
features/steps/core.py
pyproject.toml

This is to expand the Travis testing. Specifically, it adds:
- Python 3.8 (on Linux) as an "allowable failure". See #739. It looks like an easy fix to get this working. Once working, this can removed from the allowable failure list.
- the developmental version of Python (on Linux), as an allowable failure. This is designed as a forward-looking test to help us be aware of anything in the next Python version that might break `jrnl`. It also has the bonus of helping the Python core devs by exposing the cutting edge Python code to lots of real life Python code.
- a test not in UTC. When I was re-adding the DayOne tests (#742), I discovered that the code path changes depending on if the timezone is UTC or now. However, I expect few user's machines are set to UTC, so it seems like an oversight …

More Travis-CI Testing

---

features/encryption.feature
features/multiple_journals.feature
features/steps/core.py
jrnl/EncryptedJournal.py
jrnl/cli.py
jrnl/util.py

~~Stacked on #705.~~ Rebased on Master.
When creating a new password (using --encrypt), jrnl will now ask you to repeat the password. It will only encrypt it after you entered the same password correctly twice.
I've read some people complaining about permanently encrypting their journal because they mistyped their password, this should prevent that.
This does not work during the install yet, but will in #708. 
Fixes #481.

Password confirmation

---

docs/assets/theme.css

Fixes #760.
Headers were not visible because of a transparent background. This commit will give the header the same gradient treatment as the sidebar, which will expose the hamburger menu - tapping the menu shows the sidebar for navigation.

Display header in docs on mobile devices

---

.travis.yml

Closes #757
This also does the following:
- All tests run on Python 3.6, 3.7, and 3.8
- Each Python version runs on Linux, Mac and Windows
- Adds caching for Python versions installed by pyenv on mac, and choco on windows (speeds up builds considerably)
Todo (possibly in a separate PR):
- Add caching for `poetry install` (would shave off another minute or so per test suite)
- Look into why Windows python install is getting 503

Fix CI config to only deploy once

---

features/data/configs/bug153.yaml
features/data/configs/dayone.yaml
features/data/configs/empty_folder.yaml
features/data/configs/encrypted.yaml
features/data/configs/markdown-headings-335.yaml
features/data/configs/multiple.yaml
features/data/configs/tags-216.yaml
features/data/configs/tags-237.yaml
features/data/configs/tags.yaml
features/multiple_journals.feature
jrnl/EncryptedJournal.py
jrnl/Journal.py
jrnl/cli.py
jrnl/install.py
jrnl/util.py

~~Stacked on #706 and #705, merge those before merging this PR. I can also rebase on master afterwards before merging to avoid duplicate commits.~~
After working with the passwords a bit in #706, I noticed how they were sometimes stored in the same dict as all the other journal specific configuration. I also noticed how some of the test files even had password fields in them. 
I was worried that real passwords would accidentally get written to the jrnl config file in the future (and subsequently leaked through peoples dotfile repositories...). To prevent that, I refactored a lot of the code to constrict the password handling logic only to the EncryptedJournal classes and away from the other configuration that gets saved to disk. 
However, I had to change the install progress a little bit …

[Stacked on #706] Refactor password logic to prevent accidental password leakage

---

docs/usage.md

I indented the blocks of note text in the basic usage page. The note text shows up outside the block, visible on https://jrnl.sh/usage/. The changes were tested with `mkdocs`, and it all looks good.

Fix usage notes

---

CHANGELOG.md

Starts work on #724
Getting ready to implement the auto-changelog generator is easier if we
are caught up with the old changes. This was generated by running the
generator locally (with some manual tweaking of the results).
Huge shout out to @micahellison for going through and updating all of 
the PR titles to sound nice for the new changelog.

Update changelog in prep for auto changelog generator

---

jrnl/util.py

When jrnl creates a temp file to pass to the user's custom editor, it doesn't close that temp file first. This doesn't seem to be an issue on *nix, but in Windows, this makes editing impossible because the editor can't get a write lock on the file.
Fixes #790

Close temp file before passing it to editor to prevent file locking issues in Windows

---

docs/encryption.md

This change only affects documentation. Previous text explained that it was not possible to automatically prevent `jrnl` commands from being recorder by the `fish` shell (other than manually adding a leading space). New text instructs how to achieve this automatically with an abbreviation in the configuration of the `fish` shell.

Explain how fish can be configured to exclude jrnl commands from history by default

---

jrnl/util.py

Fix for #788 - changes `RuntimeError` to `PasswordDeleteError`

Fix crash while encrypting a journal on first run without saving password

---

.travis.yml

We originally pinned it to deal with a bug, but that is now resolved, so we can update poetry along with everything else

Unpin poetry

---

jrnl/plugins/yaml_exporter.py

This is split out of #159 et al to just contain those parts that extend the YAML exporter to also export DayOne metadata.
The code has been "black formatted".
Currently, `jrnl` may be stripping this metadata, so another PR (also split from #159) will be added to fix that.

[DayOne] YAML export improvements

---

.travis.yml
features/core.feature
features/dayone_regressions.feature
features/encryption.feature
features/upgrade.feature

We've been having trouble with Windows tests on Travis for a while, but I noticed some of them were passing on my local Windows machine today. Turns out I had the dreaded [autocrlf setting](https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings) set to false on my machine, whereas it defaults to true on Travis.
This PR tells Travis to keep the setting false, which prevents it from changing newlines when it checks out files. It also removes all the `skip_win` directives that were used to skip tests that were failing on Windows due to this issue.

Fix all skipped tests on Travis Windows builds by preserving newlines

---

features/dayone.feature
jrnl/DayOneJournal.py

Travis-CI (typically) runs in UTC, and UTC behaves weird compared to other timezones. This adds UTC support to the DayOne parts of the code.
Thus this re-enables the (most of) DayOne tests (all of which broke previously, because of UTC), building on #742 .
The code change is pulled from #350.

Add UTC support for failing DayOne tests

---

CHANGELOG.md
docs/encryption.md

The fish config line `abbr jrnl=" jrnl"` becomes `abbr jrnl " jrnl"`.

Fix typo in encryption docs

---

.travis.yml

In Travis Windows machines, if any unicode is displayed in the console, the program crashes with the following error:
```
Exception UnicodeEncodeError: 'charmap' codec can't encode characters in position 6-69: character maps to <undefined>
```
Tests from PR #824 have verbose definitions for pretty print, which is full of interesting unicode characters. Unfortunately, not even the @skip_win directive can bypass this problem.
This can be reproduced on a local Windows machine by piping the output to a file, like so:
```
poetry run behave > testoutput.txt
```
The solution is to set the PYTHONIOENCODING variable to UTF-8 as documented [here](https://travis-ci.community/t/unicode-on-windows/3109/2).
Now that these tests and all others are (hopefully) working in Windows, this PR also will fail …

Fix crashing unicode Travis tests on Windows and fail build if Windows tests fail

---

docs/theme/index.html
features/regression.feature

Since we moved the core repo to jrnl-org, the old links no longer work.

Update old links

---

docs/usage.md

These kinds of jokes make us look bad, and have gotten this project bad
PR on social media. It's best to get rid of them. We can still be super
glib and funny without crass jokes.

Get rid of dumb sex joke

---

.travis.yml

By the time we get to the deployment step, we've already run these tests
dozens of times. We don't need to run them yet again at deploy time.

Don't re-run tests on deployment

---

pyproject.toml

Taking out these lines earlier fixed the homebrew release, but broke
other things. So, I'm putting them back for now until we can find a
better solution.

Put back build lines in Poetry config

---

.travis.yml
features/core.feature

This emoji test was removed a while back to allow Travis Windows builds to run. They were crashing before on this test, but eventually I found that it was just a problem with piping unicode and fixed it in PR #836.

Restore emoji test

---

docs/recipes.md

Fixed links to various documentation files

Docs: Fix broken links in recipes.md

---

docs/advanced.md

**Changes**
1. Update `\` to `/` from the first code snippet from _Multiple journal files_ section.
I had copy and pasted this into my `~/.config/jrnl/jrnl.yaml` and found that journal files were created in my current working directory as `~\work.txt` and `~\journal.txt`.
Manual test
``` bash
cd /tmp
cat << HERE > ~/.config/jrnl/jrnl.yaml
journals:
default: ~\test-journal.txt
work: ~\test-work.txt
HERE
ls *.txt
jrnl at 3:30pm: Test default journal
jrnl work at 4:30pm: Test work journal
ls *.txt
echo '*.txt files should exist in your current directory (which confirms the issue!)'
rm -f *.txt
rm -f ~/test-journal.txt ~/test-work.txt
cat << HERE > ~/.config/jrnl/jrnl.yaml
journals:
default: ~/test-journal.txt
work: ~/test-work.txt
HERE
jrnl at 3:30pm: Test default journal
jrnl work at …
```

Fix configuration slashes and indentation in advanced usage documentation

---

.github/stale.yml

The pushpin better reflects the functionality (stops the issue from staling).

Update stalebot emoji to :pushpin: instead of :star:

---

docs/export.md

The previous URL was invalid. Used way back time machine, and at least at some point a redirect was set up to this site.

Update url for "beautiful timeline" in export.md

---

.travis.yml

Linux and Mac are both under 60s each, and Windows is under 1m 30s

Update travis caching to speed up builds

---

.github/FUNDING.yml
.travis.yml
CHANGELOG.md
CONTRIBUTING.md
jrnl/time.py

Fixes #878
Fixes this:
```
c:\code\jrnl\jrnl\time.py:60: SyntaxWarning: "is" with a literal. Did you mean "=="?
if flag is 1:  # Date found, but no time. Use the default time.
```
This currently works because of a quirk in the cPython implementation.

Syntax fix

---

.travis.yml

Fixes #870
Poetry errors out if we try to run a different version of Python that
what is specified in the config file. We want to run tests against the
latest Python version so we can see problems before they happen. This
fix updates the config file so Poetry will allow us to test. Nothing is
committed after the update.

Update Poetry requirements for testing latest Python version

---

features/tagging.feature
jrnl/util.py

Fixes #901 where if you do a tag search, jrnl doesn't include the tag itself in the search results. Added a test to catch this issue.

Fix regression for displaying entries during a tag search

---

docs/installation.md

Fixes #903.
As I was working on this, I also realized it doesn't even mention that Python is required to run jrnl. I added that in as well, along with the minimum version number. 

Change install doc guideline from pip to pipx

---

jrnl/DayOneJournal.py

The API of the standard library's `plistlib` changed with version 3.4 of Python, and the old API is being removed in Python 3.9. In other words, the new API is supported by all version of Python we current support (3.6 to 3.8).
This should (hopefully) allow our Python 3.9 tests to pass.
- [ n/a ] Have you written new tests for your core changes, as applicable?

Fix Python 3.9 incompatibility by updating plistlib

---

.gitignore
features/regression.feature
features/steps/export_steps.py
jrnl/plugins/markdown_exporter.py
jrnl/plugins/yaml_exporter.py

Fixes #768, Fixes #881.
If the exported entry does not have a final empty line, this will add one on export. Some Markdown parsers get picky about not having a empty line above a heading....
The newline added is `os.linesep`, so cross platform issues shouldn't arise.
Also includes tests.

Ensure exported entries end in a newline for Markdown and YAML exporters

---

.travis.yml

Updates Python 3.7.5 to 3.7.7 and 3.8.0 to 3.8.2.
~Also add the alpha 5 build of Python 3.9 as an allowable failure.~ Poetry doesn't support Python 3.9 yet. See https://github.com/python-poetry/poetry/issues/2154
- [ n/a ] The code change is tested and works locally.
- [ ? ] Tests pass. Your PR cannot be merged unless tests pass

[Travis] update Windows Python versions

---

features/delete.feature
jrnl/cli.py

The new `--delete` flag has a critical bug (#932). I'm disabling it for now to prevent new users from getting it. We'll follow this with another patch soon to bring back the flag once it's fixed.

Disable --delete due to critical bug

---

docs/theme/index.html

I noticed that the support link at the bottom of jrnl.sh points to an empty form for a new GitHub issue. This fix points it to the new issue templates, which should increase the quality of support requests and bug reports.

Change jrnl.sh GitHub new issue link to issue template chooser

---

features/data/configs/deletion_filters.yaml
features/data/journals/deletion_filters.journal
features/delete.feature
features/steps/core.py
jrnl/Journal.py
jrnl/cli.py

Fixes #932 and adds tests for deletion filter scenarios. Also reactivates delete functionality removed in #934.
[black](https://black.readthedocs.io/en/stable/) (consistent code styling). --  `poetry run black --check . --verbose --diff`
**Looks like #933 is also in progress for the same issue.**

Prevent filtered delete from deleting journal

---

features/environment.py
features/exporting.feature
features/regression.feature
features/steps/core.py
features/steps/export_steps.py

Fixes #939
This centralizes where we store all of our testing temporary files (in
`features` for now, but can easily be moved later), and cleans that central
location properly. This should result in a clean working directory after
running the testing suite.

Make sure testing cleans up after itself

---

.github/lock.yml

We have a lot of old issues, and sometimes people comment on them. These
comments get lost in the shuffle. We're going to lock old issues, and encourage
people to start new issues (referencing the old issue, if they choose) if they
have any troubles.

Add lockbot to lock comments on inactive, closed issues and prs

---

docs/encryption.md
docs/security.md
mkdocs.yml

Fixes #896. Adds a new section on privacy/security and addresses the points in the related issue.

Improve privacy, security, and encryption documentation #896

---

features/environment.py
features/steps/core.py
features/steps/export_steps.py
jrnl/DayOneJournal.py
jrnl/EncryptedJournal.py
jrnl/Entry.py
jrnl/FolderJournal.py
jrnl/Journal.py
jrnl/__main__.py
jrnl/cli.py
jrnl/install.py
jrnl/plugins/__init__.py
jrnl/plugins/fancy_exporter.py
jrnl/plugins/jrnl_importer.py
jrnl/plugins/json_exporter.py
jrnl/plugins/markdown_exporter.py
jrnl/plugins/template.py
jrnl/plugins/template_exporter.py
jrnl/plugins/text_exporter.py
jrnl/plugins/xml_exporter.py
jrnl/plugins/yaml_exporter.py
jrnl/time.py
jrnl/upgrade.py
jrnl/util.py
pyproject.toml

Recreates #917 
Applies `isort` to the codebase to organize imports. Includes the configuration used here in the project's `pyproject.toml` file so this can be reproduced, but does not add any forced linting.
- [ x ] The code change is tested and works locally.
- [ ? ] Tests pass. Your PR cannot be merged unless tests pass. --

Apply isort Mk II

---

.build/generate_changelog.sh
.build/gitlab-ci.yml
.travis.yml

Neither Travis Github Actions support manually triggering a pipeline step, so
this PR adds that step to Gitlab. It just increments the version, commits and
tags the release. Our regular Travis release process will take over after the
tag is pushed.

Use gitlab to trigger releases in pipeline

---

features/tagging.feature
jrnl/util.py

Fixes #926.
The pretty print feature (#842) highlights all tags by default, but if you search for a particular tag, it only highlights that tag. However, when searching for multiple tags, it would show the entire title and body once for each tag searched for.
This PR removes that selective highlighting (so all tags are highlighted regardless of what you've searched for) and adds a test that catches the duplication bug.

Fix duplicate text in multiple tag search

---

docs/recipes.md

typo in recipes.md. two verbs in a row. only one is needed :)
cheers
mja

Fix typo in recipes.md

---

jrnl/cli.py

This hopefully fixes #799 because prviously it would allow you to create an entry using your editor and then attempt to open the journal. This behaviour is fine for unecrypted journals but with encrypted journals it means that if you get the password wrong three times then the entry you wrote is lost.
Swapping the code around so that it attempts to open the journal before it opens an editor means that this can't happen. This should solve #270, #256 and #284 too.
It appears that this was the [behaviour in earlier versions of `jrnl`](https://github.com/jrnl-org/jrnl/blob/9618b74f8db84e7847bf15fa46838f100663db0a/jrnl/cli.py#L162) but I'm assuming that this got lost after a rewrite.
This is my first time contributing to open source so I apologise if I've formatted anything wrong or made a big …

Ask for password before adding entry instead of after

---

.github/lock.yml

Further to #938.
Should starred/[pushpinned issues](https://github.com/jrnl-org/jrnl/issues?q=is%3Aopen+is%3Aissue+label%3A%3Apushpin%3A) be immune to being closed? I think that was the purpose of that label.
Also, I think the closing text should encourage people to link back to "this" issue, so the conversation can be followed.
- [ n/a ] The code change is tested and works locally.
- [ n/a ] Tests pass. Your PR cannot be merged unless tests pass. --
- [ n/a ] The code passes linting via
- [ n/a ] The code passes linting via [pyflakes](https://launchpad.net/pyflakes)
- …

Update lockbot comment to encourage linking to issue

---

features/core.feature
features/data/configs/editor-args.yaml
features/steps/core.py
jrnl/cli.py
jrnl/util.py

Fixes #581
When the 'editor' key in the config contains an argument with a space, it used
to be parsed incorrectly. The example given in the linked issue is `vim -f -c
'setf markdown'`, which would have `'setf` and `markdown'` parsed as two
separate arguments. There was a partial fix implemented, but it left out mac
users due to a faulty platform check.
This fixes those problems and adds a test to confirm.

Fix editor config when an argument with a space is used

---

docs/usage.md

While working on it, I hard-wrapped the lines to 80 characters. Hope that doesn't complicate things.
Note: I changed the Steve Buscemi quote to maintain compliance with the Code of Conduct.

Cleaned up usage.md for clarity, formatting, and grammar.

---

.gitattributes

Related to discussion in #962, though not a fix to the original problem.
This PR ensures that all clients are checking out test data with LF line endings. This isn't an issue for *nix users, but many Windows git configurations automatically modify line endings to CRLF due to the `core.autocrlf` setting, which breaks a handful of tests.
In the past (#823) we have gotten around this by ensuring that the setting is set to preserve line endings, but that still imposes a significant barrier for Windows developers, especially since the symptom is so confusing (tests failing without any indication why).
- [n/a] I have you written new tests for these changes, as needed.

Ensure test data is always checked out with LF line endings

---

jrnl/cli.py
jrnl/install.py
jrnl/time.py
jrnl/upgrade.py
jrnl/util.py

Hi!
I noticed, that jrnl starts with a slight delay. I researched code and found some slow and rare **global** imports.
I made rare imports local and added an additional function, which checks version of jrnl.
These improvements have boosted speed by 10% and have boosted python imports by 23%. I used 
`perf stat` and `python3 -X importtime` for analyzing.
Perf stat on the develop branch:
```
[user@pc jrnl]$ echo "" > /home/user/.local/share/jrnl/journal.txt
[user@pc jrnl]$ perf stat -r 100 -d ./run test
Performance counter stats for './run test' (100 runs):
254,69 msec task-clock:u              #    0,993 CPUs utilized            ( +-  0,67% )
0      context-switches:u        #    0,000 K/sec                  
0      cpu-migrations:u          #    0,000 K/sec                  
3 363 …
```

Speed up jrnl by 10%, improve slow imports

---

features/core.feature
jrnl/util.py

This PR changes the logic for separating the title from the rest of the entry. This is intended to fix #945. 
It's important to note that we can't just remove all sentence terminal checking, because then normal command-entry breaks. When a user enters an entry at the command line, they obviously can't naturally newline, so we still have to break the sentence by terminals. However, if there is a newline, then we can infer that that was where the user truly wanted the title to end because they were writing in a full text editor.
Because of this, it is impossible to *fully* fix #945, but it is possible to fix it if there is a newline character following the sentence.
Here are some cases:
User:
`jrnl I did it! I won the competition. I am so happy`
Result: 
>2020-05-19 16:15 I did it!
>| I won …

Fix title splitting logic to account for both newlines and periods

---

features/core.feature
features/steps/core.py

This (hopefully) fixes #962 (the hanging tests on Travis).
Co-authored-by: Micah Jerome Ellison <micah.jerome.ellison@gmail.com>

Fix for hanging Windows tests on Travis

---

features/encryption.feature
features/steps/core.py
jrnl/util.py

This is intended to close #851.
There are two problems with the current keyring system:
1. The program tries to delete a password even if a password hasn't been set yet
2. Disgracefully crashes when there's no keyring backend.
This pull request solves both of those problems. 
Do note that that the new mechanism **does not** exit if a keyring backend is not found. This is because for whatever reason, the password seems to get corrupted/missing after the program crashes due to `keyring.errors.KeyringError`. 
The problem with not exiting is that if the editor is queued to pop up, the user never had an opportunity to see that their password didn't get saved. I would have just asked the user whether they wanted to continue or not, but this leads to the problem of what happens if they Ctrl-C …

Fix set_keychain errors

---

docs/overview.md

I tried to add clarity and details while maintaining the spirit of the original
document. However, it might be a bit too 'dry' now. I'd be happy to liven it up
a bit. I'm only serious when I feel like I _have_ to be.
One of my opinions (which may be at odds with yours) is that the documentation
should emphasize `jrnl`'s advantages without downplaying any other existing
solutions.
If I have time, I'd like to add more information about the documented benefits
of journaling, particularly the mental health aspects. That will probably need
its own page, but I'm new here, so I don't want to overstay my welcome. :)
(logically errors and unused imports). …

Extensive modifications to overview.md

---

features/core.feature
jrnl/EncryptedJournal.py
jrnl/Journal.py

This is intended to close #893.
It creates the directory if it does not exist. 
If the directory doesn't exist it now prints:
```
[Directory <directory> created]
[Journal <journal>  created at <filename>]
[Entry added to <journal> journal]
```
The same thing happens right before asking for a password for EncryptedJournals.
I can't really make tests for this because it requires a directory that does not exist, and creates one if it doesn't; so the test would fail once and then pass every time after that, which obviously isn't very good.

Create directory if it doesn't exist

---

features/core.feature
features/environment.py
features/steps/core.py
jrnl/install.py

Intended to close #860.
During installation, make sure the journal path is added to the config as an absolute path. I think prepending `~/` as @micahellison mentioned is very unexpected. 

Create journal with absolute path when no path is specified

---

features/exporting.feature
features/steps/export_steps.py
jrnl/plugins/json_exporter.py
jrnl/plugins/xml_exporter.py

This is intended to close #974.
It is nice to have the tags separately by entry rather than just a frequency chart which is somewhat useless except for perhaps interesting statistics.
The only exporters that support this kind of structure is JSON, XML, and YAML. YAML already has this feature.
This PR adds individually tagged entries for both xml and json. 

Add tags to json and xml exporters
