.gitignore
features/data/configs/markdown-headings-335.yaml
features/data/journals/markdown-headings-335.journal
features/exporting.feature
jrnl/cli.py
jrnl/plugins/__init__.py
jrnl/plugins/markdown_exporter.py
jrnl/plugins/tag_exporter.py
jrnl/plugins/text_exporter.py
jrnl/plugins/yaml_exporter.py
jrnl/util.py
setup.py

2.0 rc1 markdown export fix

---

README.md

Instead of pointing to homepage.
Thank you

Change README url to point to actual documentation

---

CONTRIBUTING.md

Minor grammatical fixes in the contributing doc

minor typo corrections

---

jrnl/util.py

Ok, I think I did this right...

Use shlex to parse editor commandline as per 2.0-rc1

---

README.md

Applying https://github.com/jrnl-org/jrnl/pull/542#discussion_r300880192

Update `Why keep a journal?` section

---

docs/recipes.md

New PR to address the request in #367 , but based on new Markdown docs.

Add recipe to display random entry

---

README.md
docs/advanced.md
docs/overview.md
docs/recipes.md
docs/usage.md

- Fixes #486
- Fixes some notes not being properly formatted
- Removes non-inclusive language

Smaller doc fixes

---

.travis.yml

*Short block of text containing:
- Relevant changes in text form
- related issues
- Motivation (if applicable)
- Example of usage (if applicable)
- Example of changes to config files (if applicable)

[#715] Test for automatically incrementing version in pipeline

---

.travis.yml

*Thank you for wanting to contribute! Please fill out this description as well as look at the checklist!*
*Short block of text containing:
- Relevant changes in text form
- related issues
- Motivation (if applicable)
- Example of usage (if applicable)
- Example of changes to config files (if applicable)
*

[#715] ugh

---

.travis.yml

This PR adds a bot to automatically commit the version number (from poetry) to the repo after a deployment happens on Travis.

[#715] Make bot that will auto-increment version in code after deploy

---

CHANGELOG.md
CONTRIBUTING.md
LICENSE

Fix a couple of typos and improve spelling

fix typos, spelling

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/support_request.md

*Short block of text containing:
- Adds ":new:" label to new issues
- Makes workflow easier to manage
- :new: issues should have their :new: label removed when an action is taken on them (responded/added to milestone/resolved/etc.)

Adding ":new:" label in new issue templates

---

CONTRIBUTING.md

I wanted to get the ball rolling on updating the contributing docs as per #693. Contributions and suggestions welcome!
* Adding table of contents because it's a little long (plus, some folks just want to jump straight to environment setup details at the end)
* Cleaning up markdown for readability/maintainability (we like those hashes over the hyphens, right?)
* Updating issue links to point to issue template selections instead of generic new issues
* Adding in development notes (I'd like some help here, especially with really clear yet platform-agnostic language)
- [n/a] The code change is tested and works locally.
- [n/a] Tests pass. Your PR cannot be merged unless tests pass

[GH-693] Updating developer documentation (work in progress)

---

.travis.yml
poetry.lock

Update lock file and testing suite for Python 3.8

---

docs/recipes.md

Small update to the docs removing a left-over merge conflict.

Fix merge conflict left-over

---

features/steps/core.py
jrnl/DayOneJournal.py
jrnl/EncryptedJournal.py
jrnl/Entry.py
jrnl/Journal.py
jrnl/__init__.py
jrnl/cli.py
jrnl/export.py
jrnl/install.py
jrnl/plugins/__init__.py
jrnl/plugins/fancy_exporter.py
jrnl/plugins/jrnl_importer.py
jrnl/plugins/json_exporter.py
jrnl/plugins/markdown_exporter.py
jrnl/plugins/tag_exporter.py
jrnl/plugins/template.py
jrnl/plugins/template_exporter.py
jrnl/plugins/text_exporter.py
jrnl/plugins/util.py
jrnl/plugins/xml_exporter.py
jrnl/plugins/yaml_exporter.py
jrnl/time.py
jrnl/upgrade.py
jrnl/util.py

(#770) We need to run black on the entire codebase before accepting PRs about using Black

[#770] run black formatter on codebase for standardization

---

docs/recipes.md

Remove <<<<<<< HEAD marker in recipes.md

Remove merge marker in recipes.md

---

.gitignore
jrnl/__version__.py
pyproject.toml

Changes:
- update poetry version
- add maintainer field to config
- fix poetry warning
- add version file to repo

Fix issue where jrnl would always out 'source' for version, fix Poetry config to build and publish properly

---

pyproject.toml

We don't use it, and it breaks the homebrew install.
Special thanks to @elliotmassen and @micahellison!

Remove poetry from build system in pyproject config to fix `brew install`

---

mkdocs.yml

Don't know why this was what it was. Maybe an old joke I don't get?
Either way, new description makes more sense.

Update site description

---

docs/encryption.md

Use `--add` flag in fish `abbr` command.

docs: Fix fish history instructions.

---

jrnl/cli.py

The original code for parsing an argument like `-123` (as a shortcut for `-n 123`) has bothered me for more than 6 years! (See #131). This PR moves parsing arguments to where it belongs.

Clean up shortcut for Limit

---

.travis.yml
docs/advanced.md
features/contains.feature
features/core.feature
features/data/configs/bug153.yaml
features/data/configs/invalid_color.yaml
features/data/configs/markdown-headings-335.yaml
features/data/configs/multiline-tags.yaml
features/data/configs/multiline.yaml
features/data/configs/no_colors.yaml
features/data/configs/tags-216.yaml
features/data/configs/tags-237.yaml
features/data/configs/tags.yaml
features/data/configs/unreadabledates.yaml
features/data/journals/multiline-tags.journal
features/data/journals/multiline.journal
features/steps/core.py
features/tagging.feature
features/upgrade.feature
jrnl/Entry.py
jrnl/Journal.py
jrnl/install.py
jrnl/util.py
poetry.lock
pyproject.toml

This was stuck in a temp branch due to our old merging strategy. We need to get everything into develop and master asap or we'll just end up with ever-increasing merge conflicts.

Pretty print journal entries (add color)

---

.github/FUNDING.yml
CONTRIBUTING.md

It's been a while since CONTRIBUTING was updated and there are a few missing details worth mentioning.
* Reference Code of Conduct
* Organizing CONTRIBUTING by different methods of contributing
* Add lots of useful in-line links
* Clarify branching strategy
* Explain ways in which contributors can test
* Explain PR process
* Lots of other small additions/fixes

Update and reorganize CONTRIBUTING

---

docs/theme/index.html

Small changes to the sites main page (no docs or codebase changes).

Update twitter buttons, contribution in footer

---

features/exporting.feature
jrnl/plugins/yaml_exporter.py

[YAML Exporter] fix starred spelling

---

CODE_OF_CONDUCT.md

The template we use updated to 2.0. This uses the updated template.

Update the code of conduct

---

.travis.yml
Makefile
features/steps/core.py
jrnl/EncryptedJournal.py
jrnl/FolderJournal.py
jrnl/__init__.py
jrnl/cli.py
jrnl/install.py
jrnl/plugins/jrnl_importer.py
jrnl/plugins/markdown_exporter.py
jrnl/plugins/template.py
jrnl/plugins/yaml_exporter.py
poetry.lock
pyproject.toml

Fixes #889
Fixes #770
We accidentally introduced a syntax error recently. This should help prevent
that from happening again. This also adds a check poetry can do on its own
config, because we might as well.

Expand linting step in CI

---

Makefile

The current makefile leaves out some steps that the pipeline checks. This
change will make it easier for contributors to see errors before pushing their
branch, allowing for faster iteration.

Update makefile to match pipeline better

---

docs/advanced.md

Editing the config file doesn't always destroy your journal, luckily :-)

Docs: editing config isn't always destructive

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/support_request.md
.github/PULL_REQUEST_TEMPLATE.md
issue_template.md

This PR cleans up and standardizes some of our disparate templates. It is also
an attempt to make them a bit friendlier, and more succinct. It also adds a
message if anyone attemps to create a blank issue.

Clean up templates and issues
